- hosts: all
  become: yes
  tasks:
    - name: Desative o SELinux
      selinux:
        state: disabled

    - name: Instale o nginx
      dnf:
        name: nginx
        state: latest

    - name: Inicie o nginx
      service:
        name: nginx
        state: started

    - name: Adicione o repositório Docker
      dnf:
        name: dnf-utils
        state: latest

    - name: Configurar o repositório do Docker
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Instale o Docker Engine e ferramentas associadas
      dnf:
        name:
          - git
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest

    - name: Inicie e habilite o Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Verificando dir /home/scripts
      file:
        path: /home/scripts
        state: absent

    - name: Clonando o Repositorio para /home/scripts
      git:
        repo: 'https://github.com/23Ant/ContainerWatch-Dockercomposer-scriptGO.git'
        dest: /home/scripts

    - name: Remover container 'app' se existir
      command: docker rm -f app
      ignore_errors: yes

    - name: Execute Docker Compose
      command: sudo docker compose up -d
      args:
        chdir: /home/scripts

    - name: Entrar no container 'app' e executar Go mod tidy
      command: docker exec -t app go mod tidy

    - name: Download Go modulo client_golang
      command: docker exec -t app go mod download github.com/prometheus/client_golang

    - name: Execute o aplicativo Go
      shell: docker exec -t app go run main.go > output.log 2>&1 &
      async: 0
      poll: 0